In [1]:
import numpy as np

In [2]:
np.array([[1., 0., 0.],[0., 1., 2.]])

array([[1., 0., 0.],
       [0., 1., 2.]])

In [3]:
a = np.array([[1., 0., 0.],[0., 1., 2.]])

In [4]:
a.ndim

2

In [5]:
a.shape

(2, 3)

In [6]:
a.size

6

In [7]:
a.dtype

dtype('float64')

In [8]:
a.itemsize

8

In [9]:
a.data

In [10]:
type(a)

numpy.ndarray

In [11]:
v = np.array([2,3,4])

In [12]:
t = np.array([2,3,4])

In [13]:
v + t

array([4, 6, 8])

In [14]:
z = np.zeros((4,4))

In [15]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
e = np.ones((4,4))

In [17]:
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.arange(0, 2, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [19]:
a

array([[1., 0., 0.],
       [0., 1., 2.]])

In [20]:
a[0,0]

1.0

In [21]:
a[-1,-1]

2.0

In [22]:
a[:-1,1]

array([0.])

In [23]:
a[:,1]

array([0., 1.])

In [24]:
a[:,0]

array([1., 0.])

In [25]:
a[:, 2]

array([0., 2.])

In [26]:
a[1,:]

array([0., 1., 2.])

In [27]:
import matplotlib.pyplot as plt

In [28]:
xs, ys  = range(0, 11), range(0, 11)